version: '3.5'

services:
  postgres:
    container_name: pg-e2e
    image: postgres
    environment:
      - POSTGRES_USER=task
      - POSTGRES_PASSWORD=task
      - POSTGRES_DB=taskapp
    ports:
      - '5432:5432'
